- name: Github play
  hosts: ionos
  gather_facts: true
  
  vars_prompt:

    - name: parent_directory
      prompt: Name of the parent directory
      default: kubeflow-mlops
      private: false
  
  roles:
    - remote

  handlers:
    - name: Create new files
      ansible.builtin.file:
        path: "{{ home_directory }}/ansible_test_directory/{{ item }}"
        state: touch
      loop:
        - file_2.txt
        - file_3.txt

- name: Docker check
  hosts: localhost
  gather_facts: true
  
  roles:
    - local