- name: Get services
  ansible.builtin.service_facts:

- name: Get all docker repositories
  ansible.builtin.command: >
    docker images --format "{{ '{{.Repository}}' }}"
  register: docker_images
  when: "'docker' in ansible_facts.services"

- name: List all images
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ docker_images.stdout_lines }}"
  when: (docker_images is defined) and item != '<none>'