- name: Get services
  ansible.builtin.service_facts:
  tags: services

- name: Get all docker repositories
  ansible.builtin.command: >
    docker images --format "{{ '{{.Repository}}' }}"
  register: docker_images
  when: "'docker' in ansible_facts.services"
  tags: services

- name: List all images
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ docker_images.stdout_lines }}"
  when: (docker_images is defined) and item != '<none>'
  tags: services

- name: Check if sudo user exists on system
  ansible.builtin.getent:
    database: passwd
    key: ssafarveisi
  tags: sudo 

- name: Return the info from db provider
  ansible.builtin.debug:
    msg: "{{ ansible_facts.getent_passwd }}"
  tags: sudo

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull
  tags: docker_container

- name: Create default containers
  community.docker.docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    debug: true
    auto_remove: true
    cleanup: true
    detach: false
    state: present
  with_sequence: count={{ container_count }}
  tags: docker_container